---
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/bin
    - $(npm config get prefix)/lib/node_modules
install:
  - npm i -g serverless npx
  - sls dynamodb install
  - make install
script:
  - make test-coverage
  - cat coverage/lcov.info | coveralls
  - sls dynamodb start & sleep 5
  - make integration-test
  - make deploy
  - make deploy-production
branches:
  only:
    - master
