---
language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/travis/.nvm
    - node_modules
script:
  - npm install -g serverless npx
  - sls dynamodb install
  - make install
  - make test-coverage
  - cat coverage/lcov.info | npx coveralls
  - sls dynamodb start --detached
  - make integration-test
  - sls dynamodb stop
  - make deploy
branches:
  only:
    - master
