---
language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
script:
  - npm install -g serverless
  - make install
  - make test
  - make deploy
branches:
  only:
    - master
