---
language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/travis/.nvm
    - node_modules
script:
  - npm install -g serverless npx
  - make install
  - make test-coverage
  - cat coverage/lcov.info | npx coveralls
  - make deploy
branches:
  only:
    - master
