---
service: todo-example

frameworkVersion: ">=1.1.0 <2.0.0"

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: serverless-example-todos

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        Fn::GetAtt:
          - TodosDynamoDbTable
          - Arn

functions:
  create:
    handler: dist/create.default
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: dist/list.default
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: dist/get.default
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: dist/update.default
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: dist/delete.default
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
