---
service: serverless-example-todos

frameworkVersion: ">=1.1.0 <2.0.0"

resources:
  Resources:
    todoExampleTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: serverless-example-todos

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt:
          - todoExampleTable
          - Arn
  environment:
    AWS_REGION: ${file(./serverless.env.yml):dev.AWS_REGION}

functions:
  create:
    handler: src/handlers/create.default
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: src/handlers/list.default
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: src/handlers/get.default
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: src/handlers/update.default
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: src/handlers/delete.default
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
